from ibm_watsonx_ai.foundation_models import ModelInference
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watsonx_ai.metanames import EmbedTextParamsMetaNames
from ibm_watsonx_ai import Credentials
from langchain_ibm import WatsonxLLM, WatsonxEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_community.document_loaders import PyPDFLoader
from langchain.chains import RetrievalQA
from huggingface_hub import HfFolder

import gradio as gr

# You can use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

## LLM
def get_llm():
    model_id = 'ibm/granite-3-2-8b-instruct'
    parameters = {
        GenParams.MAX_NEW_TOKENS: 512,
        GenParams.TEMPERATURE: 0.5
    }
    project_id = "skills-network"
    watsonx_llm = WatsonxLLM(
        model_id=model_id
        , url = "https://us-south.ml.cloud.ibm.com"
        , project_id = project_id
        , params = parameters
    )

    return watsonx_llm

## Document loader
def document_loader(file):
    loader = PyPDFLoader(file)
    loaded_document = loader.load()

    return loaded_document

## Text splitter
def text_splitter(data):
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size = 1000
        , chunk_overlap = 200
        # , lenght_function # as it has a default value 'len'
    )
    chunks = text_splitter.split_documents(data)
    return chunks

## Embedding model
def watsons_embedding():
    embed_params = {
        EmbedTextParamsMetaNames.TRUNCATE_INPUT_TOKENS: 3,
        EmbedTextParamsMetaNames.RETURN_OPTIONS: {
            'input_text': True # Include text in response
        }
    }

    watsonx_embedding = WatsonxEmbeddings(
        model_id="ibm/slate-125m-english-rtrvr-v2"
        , url="https://us-south.ml.cloud.ibm.com"
        , project_id="skills-network"
        , params=embed_params
    )
    return watsonx_embedding

## Vector db
def vector_database(chunks):
    clean_chunks = [doc for doc in chunks if doc.page_content.strip()] # to remove the chunks with no content
    embedding_model = watsons_embedding()
    vector_db = Chroma.from_documents(
        clean_chunks, embedding_model
    )
    return vector_db

## Retriever
def retriever(file):
    splits = document_loader(file)
    chunks = text_splitter(splits)
    vector_db = vector_database(chunks)
    retriever = vector_db.as_retriever()
    return retriever

## QA Chain
def retriever_qa(file, query):
    llm = get_llm()
    retriever_obj = retriever(file)
    qa = RetrievalQA.from_chain_type(llm=llm, 
                                    chain_type="stuff", 
                                    retriever=retriever_obj, 
                                    return_source_documents=False
    )
    response = qa.invoke(query)
    return response['result']

# Create Gradio interface
rag_application = gr.Interface(
    fn=retriever_qa,
    #allow_flagging=.....,
    inputs=[
        gr.File(label="Upload PDF File", file_count="single", file_types=['.pdf'], type="filepath"),  # Drag and drop file upload
        gr.Textbox(label="Input Query", lines=2, placeholder="Type your question here...")
    ],
    outputs=gr.Textbox(label="Answer from LLM"),
    title="QA Chat bot",
    description="Upload a PDF document and ask any question. The chatbot will try to answer using the provided document."
)

if __name__ == "__main__":
    rag_application.launch(
        server_name = "127.0.0.1"
        , server_port = 7860
    )